# This cript generates 10 mFC tables to use in the F35 permutations
# iT starts from the F35 (or FMSY proxy) vector generated by the 96 runs
# It permutes this vector to 10 vectors, scaling each F35 by seq(0,2,0.2)
library(tidyverse)

# NB: input values of F are not the same as F as perceived by the model, aka the F calculated from the exploitation rate and used on the x-axis of the yield curves
# In other words, to achieve F35 we need to hit the model with F35'. 
# So, the F35 vector is, in fact, an F35' vector. 

# Read F35 vector
f_vec <- read.csv("NOAA_Azure/data/f35_vector_PROXY.csv")

# Read f-lookup table for mFC - so we don't have to make the conversion
f_lookup <- read.csv("NOAA_Azure/data/f_lookup_4.csv")

# read fg
grp <- read.csv('NOAA_Azure/data/GOA_Groups.csv') # functional groups

# join the two
f_mfc_vec <- f_vec %>%
  left_join(grp %>% select(Code, LongName), by = "LongName") %>%
  left_join(f_lookup, by = c("Code"="species", "fidx"))

mfc_vec <- f_mfc_vec %>%
  select(Code, LongName, mfc)

# permute
maxmult <- 4
mult <- seq(0,4,length.out=11)

perm_frame <- data.frame(matrix(nrow = length(mfc_vec$Code), ncol = length(mult)+1))
colnames(perm_frame) <- c('Code',paste0('p',1:11)) 

for(i in 1:length(mfc_vec$Code)){
  
  this_sp <- mfc_vec$Code[i]
  this_mfc <- mfc_vec %>% filter(Code == this_sp) %>% pull(mfc)
  mfc_perm <- this_mfc * mult
  perm_frame[i,1] <- this_sp
  perm_frame[i,2:ncol(perm_frame)] <- mfc_perm
  
}

# Write mFC matrix --------------------------------------------------------
nfleet <- 33 # how many fleets in the harvest.prm file?
select <- dplyr::select

# for species that aren't the Tier 3 stocks (focus of this effort), we need to pull old values (1/4 M)
# read in the desired harvest.prm file. Take one from the F tests, as those have the correct startage and mFC for other species 
# NB: make sure the background values coinceide between the SS and MS runs. That is, change this when we finally update this with improved SS runs.
harvest <- readLines("goa_runs/AtlantisGOA_F_test/GOA_harvest_1.prm")
# the string we use to split the file is "# Forced fishing mortality rates - one entry per fishery". This may change in other models
mfc_start <- grep("# Forced fishing mortality rates - one entry per fishery", harvest)
# the end of the mFC matrix is "mFC_DR 33" (which BTW we don't need, together with some others, but it won't hurt there). This may change in other models
mfc_end <- grep("mFC_DR 33", harvest)+1
# get the old mFC matrix
mfc_mat_old <- harvest[mfc_start:mfc_end]
# get the head and the tail of the harvest.prm file
harvest_head <- harvest[1:mfc_start-1]
harvest_tail <- harvest[mfc_end+1: length(harvest)]

# create a folder where we will store these
dir.create(paste0("NOAA_Azure/code/f35_perms/", maxmult, "/"))

# loop over species one at a time. Do all species
fg <- grp$Code
fg_t3 <- perm_frame$Code

for(i in 1:length(mult)){
  
  # create file
  newfile <-  paste0("NOAA_Azure/code/f35_perms/", maxmult, '/GOA_harvest_f35_', i, '.prm')
  
  file.create(newfile)
  
  new_mfc_mat <- "# Forced fishing mortality rates - one entry per fishery"
  
  for(j in 1:length(fg)){
    
    this_fg <- fg[j]
    
    this_mfc_name <- paste0('mFC_',this_fg,' 33')
    
    if(this_fg %in% fg_t3){
      this_mfc <- perm_frame %>% filter(Code == this_fg) %>% select(i+1) %>% pull()
      this_mfc_vec <- paste(as.character(c(this_mfc, rep(0, nfleet-1))), collapse = " ")
    } else {
      this_mfc_vec <- mfc_mat_old[grep(this_mfc_name, mfc_mat_old)+1]
    }
    
    new_mfc_mat <- c(new_mfc_mat, this_mfc_name, this_mfc_vec)
  }
  
  # paste the head and tail of the harvest.prm file
  new_harvest <- c(harvest_head, new_mfc_mat, harvest_tail)
  
  # write this to file
  writeLines(new_harvest, con = newfile)
  
}

# optional lines to take a set of already generated F35 permutations and create a new set where ATF is fixed to background values
# Careful with what you choose for background values
harvest_bg <- readLines("NOAA_Azure/data/GOA_harvest_background.prm")
atf_mfc_bg <- harvest_bg[grep("mFC_ATF 33",harvest_bg)+1]

# make ATF folder as a copy of an existing folder
dir.create("NOAA_Azure/code/f35_perms/4-ATF-low")

# files to change
files_atf <- list.files("NOAA_Azure/code/f35_perms/4", full.names = T)
# reorder these based on the number in the filename
num_idx <- as.numeric(sub(".*_([0-9]+)\\.prm", "\\1", files_atf))
files_atf <- files_atf[order(num_idx)]

# change the line for ATF for each of these files
for(i in 1:length(files_atf)){
  
  # create file
  newfile <-  paste0("NOAA_Azure/code/f35_perms/", maxmult, '-ATF-low/GOA_harvest_f35_', i, '_ATF.prm')
  
  file.create(newfile)
  
  to_change <- readLines(files_atf[i])
  
  # which line do we need to change?
  to_change[grep("mFC_ATF 33",to_change)+1] <- atf_mfc_bg
  
  # write this to file
  writeLines(to_change, con = newfile)
  
}

# now copy all these over to a folder based on AtlantisGOA_F_test
# NB: Careful - when we do this for real you'll want to make sure you base it on a folder like the OY ones - make sure biological parameters are consistent between SS and MS

